config/routes.rb
Rails.application.routes.draw do
  resources :accions
  resources :objetivos
  resources :lineamientos
  get 'welcome/index'

  root 'welcome#index'

end

app/models/accion.rb
class Accion < ActiveRecord::Base
  belongs_to :objetivo
end

app/models/lineamiento.rb
class Lineamiento < ActiveRecord::Base
  has_many :objetivos
end

app/models/objetivo.rb
class Objetivo < ActiveRecord::Base
  belongs_to :lineamiento

  has_many :accions
end

app/controllers/accions_controller.rb
class AccionsController < ApplicationController
  before_action :set_accion, only: [:show, :edit, :update, :destroy]

  # GET /accions
  # GET /accions.json
  def index
    @accions = Accion.all
  end

  # GET /accions/1
  # GET /accions/1.json
  def show
  end

  # GET /accions/new
  def new
    @accion = Accion.new
  end

  # GET /accions/1/edit
  def edit
  end

  # POST /accions
  # POST /accions.json
  def create
    @accion = Accion.new(accion_params)

    respond_to do |format|
      if @accion.save
        format.html { redirect_to @accion, notice: 'Accion was successfully created.' }
        format.json { render :show, status: :created, location: @accion }
      else
        format.html { render :new }
        format.json { render json: @accion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accions/1
  # PATCH/PUT /accions/1.json
  def update
    respond_to do |format|
      if @accion.update(accion_params)
        format.html { redirect_to @accion, notice: 'Accion was successfully updated.' }
        format.json { render :show, status: :ok, location: @accion }
      else
        format.html { render :edit }
        format.json { render json: @accion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accions/1
  # DELETE /accions/1.json
  def destroy
    @accion.destroy
    respond_to do |format|
      format.html { redirect_to accions_url, notice: 'Accion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_accion
      @accion = Accion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def accion_params
      params.require(:accion).permit(:nombre, :porcentaje_realizado, :objetivo_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lineamientos_controller.rb
class LineamientosController < ApplicationController
  before_action :set_lineamiento, only: [:show, :edit, :update, :destroy]

  # GET /lineamientos
  # GET /lineamientos.json
  def index
    @lineamientos = Lineamiento.all
  end

  # GET /lineamientos/1
  # GET /lineamientos/1.json
  def show
  end

  # GET /lineamientos/new
  def new
    @lineamiento = Lineamiento.new
  end

  # GET /lineamientos/1/edit
  def edit
  end

  # POST /lineamientos
  # POST /lineamientos.json
  def create
    @lineamiento = Lineamiento.new(lineamiento_params)

    respond_to do |format|
      if @lineamiento.save
        format.html { redirect_to @lineamiento, notice: 'Lineamiento was successfully created.' }
        format.json { render :show, status: :created, location: @lineamiento }
      else
        format.html { render :new }
        format.json { render json: @lineamiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lineamientos/1
  # PATCH/PUT /lineamientos/1.json
  def update
    respond_to do |format|
      if @lineamiento.update(lineamiento_params)
        format.html { redirect_to @lineamiento, notice: 'Lineamiento was successfully updated.' }
        format.json { render :show, status: :ok, location: @lineamiento }
      else
        format.html { render :edit }
        format.json { render json: @lineamiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lineamientos/1
  # DELETE /lineamientos/1.json
  def destroy
    @lineamiento.destroy
    respond_to do |format|
      format.html { redirect_to lineamientos_url, notice: 'Lineamiento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lineamiento
      @lineamiento = Lineamiento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lineamiento_params
      params.require(:lineamiento).permit(:nombre)
    end
end

app/controllers/objetivos_controller.rb
class ObjetivosController < ApplicationController
  before_action :set_objetivo, only: [:show, :edit, :update, :destroy]

  # GET /objetivos
  # GET /objetivos.json
  def index
    @objetivos = Objetivo.all
  end

  # GET /objetivos/1
  # GET /objetivos/1.json
  def show
  end

  # GET /objetivos/new
  def new
    @objetivo = Objetivo.new
    @lineamientos = Lineamiento.all
  end

  # GET /objetivos/1/edit
  def edit
  end

  # POST /objetivos
  # POST /objetivos.json
  def create
    @objetivo = Objetivo.new(objetivo_params)

    respond_to do |format|
      if @objetivo.save
        format.html { redirect_to @objetivo, notice: 'Objetivo was successfully created.' }
        format.json { render :show, status: :created, location: @objetivo }
      else
        format.html { render :new }
        format.json { render json: @objetivo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /objetivos/1
  # PATCH/PUT /objetivos/1.json
  def update
    respond_to do |format|
      if @objetivo.update(objetivo_params)
        format.html { redirect_to @objetivo, notice: 'Objetivo was successfully updated.' }
        format.json { render :show, status: :ok, location: @objetivo }
      else
        format.html { render :edit }
        format.json { render json: @objetivo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /objetivos/1
  # DELETE /objetivos/1.json
  def destroy
    @objetivo.destroy
    respond_to do |format|
      format.html { redirect_to objetivos_url, notice: 'Objetivo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_objetivo
      @objetivo = Objetivo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def objetivo_params
      params.require(:objetivo).permit(:nombre, :lineamiento_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/accions_helper.rb
module AccionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lineamientos_helper.rb
module LineamientosHelper
end

app/helpers/objetivos_helper.rb
module ObjetivosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/accions/_form.html.erb
<%= simple_form_for(@accion) do |f| %>
  <% if @accion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@accion.errors.count, "error") %> prohibited this accion from being saved:</h2>

      <ul>
      <% @accion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :porcentaje_realizado %><br>
    <%= f.number_field :porcentaje_realizado %>
  </div>
  <div class="field">
    <%= f.input :objetivo_id, collection: Objetivo.all.collect { |p| [ p.nombre, p.id ] }, label: 'Objetivo'%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accions/edit.html.erb
<h1>Editing Accion</h1>

<%= render 'form' %>

<%= link_to 'Show', @accion %> |
<%= link_to 'Back', accions_path %>

app/views/accions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Accions</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Porcentaje realizado</th>
      <th>Objetivo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accions.each do |accion| %>
      <tr>
        <td><%= accion.nombre %></td>
        <td><%= accion.porcentaje_realizado %></td>
        <td><%= accion.objetivo %></td>
        <td><%= link_to 'Show', accion %></td>
        <td><%= link_to 'Edit', edit_accion_path(accion) %></td>
        <td><%= link_to 'Destroy', accion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Accion', new_accion_path %>

app/views/accions/new.html.erb
<h1>New Accion</h1>

<%= render 'form' %>

<%= link_to 'Back', accions_path %>

app/views/accions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @accion.nombre %>
</p>

<p>
  <strong>Porcentaje realizado:</strong>
  <%= @accion.porcentaje_realizado %>
</p>

<p>
  <strong>Objetivo:</strong>
  <%= @accion.objetivo %>
</p>

<%= link_to 'Edit', edit_accion_path(@accion) %> |
<%= link_to 'Back', accions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GpRedmineParcial</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lineamientos/_form.html.erb
<%= form_for(@lineamiento) do |f| %>
  <% if @lineamiento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lineamiento.errors.count, "error") %> prohibited this lineamiento from being saved:</h2>

      <ul>
      <% @lineamiento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lineamientos/edit.html.erb
<h1>Editing Lineamiento</h1>

<%= render 'form' %>

<%= link_to 'Show', @lineamiento %> |
<%= link_to 'Back', lineamientos_path %>

app/views/lineamientos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Lineamientos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lineamientos.each do |lineamiento| %>
      <tr>
        <td><%= lineamiento.nombre %></td>
        <td><%= link_to 'Show', lineamiento %></td>
        <td><%= link_to 'Edit', edit_lineamiento_path(lineamiento) %></td>
        <td><%= link_to 'Destroy', lineamiento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lineamiento', new_lineamiento_path %>

app/views/lineamientos/new.html.erb
<h1>New Lineamiento</h1>

<%= render 'form' %>

<%= link_to 'Back', lineamientos_path %>

app/views/lineamientos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @lineamiento.nombre %>
</p>

<%= link_to 'Crear Objetivo', new_objetivo_path %> <br />
<%= link_to 'Listar Objetivos', objetivos_path %> <br />

<br />

<%= link_to 'Edit', edit_lineamiento_path(@lineamiento) %> |
<%= link_to 'Back', lineamientos_path %>

app/views/objetivos/_form.html.erb
<%= simple_form_for(@objetivo) do |f| %>
  <% if @objetivo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@objetivo.errors.count, "error") %> prohibited this objetivo from being saved:</h2>

      <ul>
      <% @objetivo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.input :lineamiento_id, collection: Lineamiento.all.collect { |p| [ p.nombre, p.id ] }, label: 'Lineamiento'%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/objetivos/edit.html.erb
<h1>Editing Objetivo</h1>

<%= render 'form' %>

<%= link_to 'Show', @objetivo %> |
<%= link_to 'Back', objetivos_path %>

app/views/objetivos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Objetivos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Lineamiento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @objetivos.each do |objetivo| %>
      <tr>
        <td><%= objetivo.nombre %></td>
        <td><%= objetivo.lineamiento %></td>
        <td><%= link_to 'Show', objetivo %></td>
        <td><%= link_to 'Edit', edit_objetivo_path(objetivo) %></td>
        <td><%= link_to 'Destroy', objetivo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Objetivo', new_objetivo_path %>

app/views/objetivos/new.html.erb
<h1>New Objetivo</h1>

<%= render 'form' %>

<%= link_to 'Back', objetivos_path %>

app/views/objetivos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @objetivo.nombre %>
</p>

<p>
  <strong>Lineamiento:</strong>
  <%= @objetivo.lineamiento %>
</p>

<%= link_to 'Crear Acción', new_accion_path %> <br />
<%= link_to 'Listar Acciones', accions_path %> <br />

<br />

<%= link_to 'Edit', edit_objetivo_path(@objetivo) %> |
<%= link_to 'Back', objetivos_path %>

app/views/welcome/index.html.erb
<h1>Bienvenido a GP</h1>
<p>desde este panel podés crear lineamientos</p>

<%= link_to 'Nuevo Lineamiento', new_lineamiento_path %> <br />
<%= link_to 'Listar Lineamientos', lineamientos_path %>